// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TayNinhTourApi.DataAccessLayer.Contexts;

#nullable disable

namespace TayNinhTourApi.DataAccessLayer.Migrations
{
    [DbContext(typeof(TayNinhTouApiDbContext))]
    partial class TayNinhTouApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
#pragma warning restore 612, 618
        }
    }
}
